# We want the height to be from 4.5 ft to 6ft

In [20]:
import pandas as pd
df = pd.read_csv('weight-height-outliers.csv')
df['height'] = df["Height"]/12
df.drop(['Weight','Height'],axis =1, inplace = True)
df.head()

  Gender    height
0   Male  8.558197
1   Male  3.165349
2   Male  7.570713
3   Male  5.977582
4   Male  5.823483

In [21]:
df.shape

(10000, 2)

In [22]:
df.describe()

             height
count  10000.000000
mean       5.530753
std        0.323434
min        3.165349
25%        5.292064
50%        5.526486
75%        5.764522
max        8.558197

# Removing outliers using IQR

In [26]:
Q1 = df.height.quantile(0.25)
Q3 = df.height.quantile(0.75)

In [28]:
IQR = Q3-Q1
IQR

np.float64(0.47245742554838976)

In [29]:
lower_bound = Q1 - 1.5*IQR
lower_bound

np.float64(4.583378246698584)

In [30]:
upper_bound = Q1 + 1.5*IQR
upper_bound

np.float64(6.000750523343753)

In [32]:
df1 = df[(df.height < upper_bound) & (df.height > lower_bound)]
df1.shape

(9272, 2)

In [34]:
df.shape[0] - df1.shape[0]

728

### 728 Outliers detected

Therefore we now have df without any outliers : df1

In [38]:
df1.describe()

            height
count  9272.000000
mean      5.484704
std       0.283242
min       4.595713
25%       5.273301
50%       5.493738
75%       5.708801
max       6.000481